FROM mysql:5.6

ENV MYSQL_ROOT_PASSWORD=liyi
ENV MYSQL_DATABASE=oscar_mcmaster
ENV MYSQL_USER=oscar
ENV MYSQL_PASSWORD=oscar

COPY oscar/database/mysql /tmp/mysql
COPY oscar/database/mysql/caisi /tmp/caisi
COPY oscar/database/mysql/updates /tmp/updates

RUN cat /tmp/mysql/oscarinit.sql /tmp/mysql/oscarinit_on.sql /tmp/mysql/oscardata.sql \
		/tmp/mysql/oscardata_on.sql /tmp/mysql/icd10.sql /tmp/caisi/initcaisi.sql \
		/tmp/mysql/icd10_issue_groups.sql \
		/tmp/mysql/measurementMapData.sql /tmp/mysql/expire_oscardoc.sql \
		>> /tmp/mysql/oscar.sql
RUN cat /tmp/updates/u*.sql >> /tmp/mysql/oscar.sql
RUN cat /tmp/updates/h*.sql >> /tmp/mysql/oscar.sql

RUN sed -i 's/insert into/INSERT IGNORE INTO/gI' /tmp/mysql/oscar.sql

RUN cp /tmp/mysql/oscar.sql /docker-entrypoint-initdb.d/oscar.sql

CMD ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_general_ci"]
